version: "3"

services:
  tezedge-node:
    image: tezedge/tezedge:v2.0.0
    pid: host
    network_mode: host
    container_name: tezedge-node-${CONTEXT_TYPE-irmin}-${TEZOS_NETWORK-ithaca}
    stop_signal: SIGINT
    command: [
      "--network", "${TEZOS_NETWORK-ithaca}",
      "--p2p-port=9999",
      "--rpc-port=19999",
      "--websocket-address=0.0.0.0:4999",
      "--log", "terminal", "file",
      "--log-file", "/tmp/tezedge/tezedge.log",
      "--tezos-context-storage", "${CONTEXT_TYPE-irmin}",
      "--peer-thresh-low", "60",
      "--peer-thresh-high", "80"
    ]
    logging:
      # Produce syslogs instead of terminal logs
      driver: "syslog"
      options:
        # Send the logs to syslog (UDP only) server (running on debugger)
        syslog-address: "udp://0.0.0.0:10001"  # Port must match debugger syslog port in 'ports' section
        # Always in same RFC 5424 format (with microseconds precision)
        syslog-format: "rfc5424micro"
    volumes:
      - "${TEZEDGE_VOLUME_PATH}:/tmp/tezedge"

  tezedge-snapshots:
    image: tezedge/tezedge-snapshots
    network_mode: host
    container_name: tezedge-snapshots-${CONTEXT_TYPE-irmin}-${TEZOS_NETWORK-ithaca}
    stop_signal: SIGINT
    environment:
      - TEZEDGE_SNAPSHOTS_VOLUME_PATH=${TEZEDGE_SNAPSHOTS_VOLUME_PATH}
      - TEZEDGE_VOLUME_PATH=${TEZEDGE_VOLUME_PATH}
    command: [
      "--tezedge-node-url", "http://localhost:19999",
      "--snapshot-frequency", "300",
      "--network", "${TEZOS_NETWORK-ithaca}",
      "--full-snapshot-image", "tezedge/tezedge:v2.0.0",
      "--context-type", "${CONTEXT_TYPE-irmin}",
      "--snapshot-frequency", "43200", # 2 times per day 43200s -> 12h
      "--snapshot-capacity", "2"
    ]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${TEZEDGE_VOLUME_PATH}:/tmp/tezedge"
      - "${TEZEDGE_SNAPSHOTS_VOLUME_PATH}:/tmp/snapshots"

    depends_on:
      - "tezedge-node"

  explorer:
    image: tezedge/tezedge-explorer:v1.9.0
    environment:
      # need a better way to provide such information
      - API=[{"id":"rust","type":"tezedge","name":"rust.${NODE_HOSTNAME_OR_IP}","http":"http://${NODE_HOSTNAME_OR_IP}:19999","p2p_port":9999,"features":[{"name":"ws","url":"ws://${NODE_HOSTNAME_OR_IP}:4999"},{"name":"monitoring"},{"name":"resources/system","monitoringUrl":"http://${NODE_HOSTNAME_OR_IP}:39999/resources/tezedge"},{"name":"resources/memory","memoryProfilerUrl":"http://${NODE_HOSTNAME_OR_IP}:17832"},{"name":"mempool"},{"name":"network"}]},{"id":"ocaml","type":"octez","name":"ocaml.${NODE_HOSTNAME_OR_IP}","http":"http://${NODE_HOSTNAME_OR_IP}:18733","p2p_port":9733,"features":[{"name":"monitoring"},{"name":"resources/system","monitoringUrl":"http://${NODE_HOSTNAME_OR_IP}:39999/resources/ocaml"},{"name":"resources/memory","memoryProfilerUrl":"http://${NODE_HOSTNAME_OR_IP}:17832"},{"name":"mempool"},{"name":"network"}]}]
    ports:
      - "8889:80"

  monitoring:
    privileged: true
    container_name: tezedge-node-monitoring-${CONTEXT_TYPE-irmin}-${TEZOS_NETWORK-ithaca}
    network_mode: host
    image: tezedge/node-monitoring:v1.9.1
    pid: "host"
    command: [
      "--tezedge-nodes", "tezedge:19999:/tmp/tezedge",
      "--wait-for-nodes",
      "--rpc-port", "39999",
    ]
    volumes:
      - "${TEZEDGE_VOLUME_PATH}:/tmp/tezedge"
