FROM debian:10 as build-env
USER root
RUN apt-get update && apt-get install -y libssl-dev pkg-config git curl clang libclang-dev

ARG rust_toolchain="1.58.1"
RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain ${rust_toolchain} -y
ENV PATH=/root/.cargo/bin:$PATH

# TODO: make repository public + build from cloned repo
COPY . /opt

RUN cd /opt/src && cargo build --release

FROM gcr.io/distroless/cc-debian10

COPY --from=build-env /opt/target/release/tezedge-snapshots /

ENTRYPOINT [ "/tezedge-snapshots" ]
