version: "3"

services:
  tezedge-node:
    image: tezedge/tezedge:v1.9.1
    pid: host
    network_mode: host
    container_name: tezedge-node
    stop_signal: SIGINT
    command: [
      "--network", "${TEZOS_NETWORK-florencenet}",
      "--p2p-port=9732",
      "--rpc-port=18732",
      "--websocket-address=0.0.0.0:4927",
      "--log", "terminal", "file",
      "--log-file", "/tmp/tezedge/tezedge.log",
      "--tezos-context-storage", "irmin",
      "--context-stats-db-path", "context-stats-db",
      "--peer-thresh-low", "60",
      "--peer-thresh-high", "80"
    ]
    volumes:
      - "/satassd/snapshot-test-data/tezedge:/tmp/tezedge"
  
  tezedge-snapshots:
    image: tezedge/tezedge-snapshots
    network_mode: host
    container_name: tezedge-snapshots
    stop_signal: SIGINT
    command: [
      "--tezedge-node-url", "http://localhost:18732",
      "--tezedge-database-directory", "/tmp/tezedge/",
      "--snapshots-target-directory", "/tmp/snapshots",
      "--snapshot-frequency", "300"
    ]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/satassd/snapshot-test-data/tezedge:/tmp/tezedge"
      - "/satassd/snapshot-test-data/snapshots:/tmp/snapshots"

    depends_on:
      - "tezedge-node"

  explorer:
    image: tezedge/tezedge-explorer:v1.9.0
    environment:
      # need a better way to provide such information
      - API=[{"id":"rust","type":"tezedge","name":"rust.${NODE_HOSTNAME_OR_IP}","http":"http://${NODE_HOSTNAME_OR_IP}:18732","p2p_port":9732,"features":[{"name":"ws","url":"ws://${NODE_HOSTNAME_OR_IP}:4927"},{"name":"monitoring"},{"name":"resources/system","monitoringUrl":"http://${NODE_HOSTNAME_OR_IP}:38732/resources/tezedge"},{"name":"resources/memory","memoryProfilerUrl":"http://${NODE_HOSTNAME_OR_IP}:17832"},{"name":"mempool"},{"name":"network"}]},{"id":"ocaml","type":"octez","name":"ocaml.${NODE_HOSTNAME_OR_IP}","http":"http://${NODE_HOSTNAME_OR_IP}:18733","p2p_port":9733,"features":[{"name":"monitoring"},{"name":"resources/system","monitoringUrl":"http://${NODE_HOSTNAME_OR_IP}:38732/resources/ocaml"},{"name":"resources/memory","memoryProfilerUrl":"http://${NODE_HOSTNAME_OR_IP}:17832"},{"name":"mempool"},{"name":"network"}]}]
    ports:
      - "8080:80"

  monitoring:
    privileged: true
    container_name: tezedge-node-monitoring
    network_mode: host
    image: tezedge/node-monitoring:v1.9.1
    pid: "host"
    command: [
      "--tezedge-nodes", "tezedge:18732:/tmp/tezedge",
      "--wait-for-nodes",
      "--rpc-port", "38732",
    ]
    volumes:
      - "/satassd/snapshot-test-data/tezedge:/tmp/tezedge"